module

import FiniteTests
import RationalQueryCompiler
import IntegerQueryAdapter
import BooleanFormula
import FiniteGroundTests

/- Inspect theorem types as well as axioms: hypotheses remain hypotheses even
when the axiom report contains only Lean's standard foundational axioms. -/
#check @H10FiniteTests.re_exists_nat_of_computable
#check @H10FiniteTests.decision_transfer
#check @H10FiniteTests.undecidable_target
#check @H10RationalCompiler.compile_correct
#check @H10RationalCompiler.constraintSystem_computable
#check @H10RationalCompiler.indexed_constraintSystem_computable
#check @H10RationalQueryAdapter.integerCoefficientValue_eq_intCast
#check @H10RationalQueryAdapter.globalDenominator_pos
#check @H10RationalQueryAdapter.normalizeToInteger_preserves_roots
#check @H10RationalQueryAdapter.normalizeToInteger_support_bounded
#check @H10RationalQueryAdapter.variableSupport_index_dense
#check @H10RationalQueryAdapter.primrec_normalizeToInteger
#check @H10RationalQueryAdapter.rationalRoot_computable_of_h10Q
#check @H10RationalQueryAdapter.constraintSystem_computable_of_h10Q
#check @H10RationalQueryAdapter.indexed_constraintSystem_computable_of_h10Q
#check @H10RationalFormula.formula_to_dnf_correct
#check @H10RationalFormula.primrec_toDNF
#check @H10RationalFormula.formulaSatisfies_computable_of_h10Q
#check @H10RationalFormula.indexed_formulaSatisfies_computable_of_h10Q
#check @H10RationalGroundTests.primrec_applicationTerm
#check @H10RationalGroundTests.applicationTerm_injective
#check @H10RationalGroundTests.applicationTerm_gt_arg
#check @H10RationalGroundTests.applicationTerm_not_arg
#check @H10RationalGroundTests.primrec_evaluateTermCode
#check @H10RationalGroundTests.validTermCode
#check @H10RationalGroundTests.ValidTermCode
#check @H10RationalGroundTests.ValidQFCode
#check @H10RationalGroundTests.ValidPrenexAxiom
#check @H10RationalGroundTests.ValidPositiveExistential
#check @H10RationalGroundTests.primrec_skolemTerm
#check @H10RationalGroundTests.primrec_skolemPrefixStep
#check @H10RationalGroundTests.primrec_skolemPrefix
#check @H10RationalGroundTests.primrec_substituteTerm
#check @H10RationalGroundTests.primrec_substituteQFToken
#check @H10RationalGroundTests.rootPolynomialValue_eq_integerPolynomialValue
#check @H10RationalGroundTests.primrec_rootPolynomial
#check @H10RationalGroundTests.primrec_rootQueryFormula
#check @H10RationalGroundTests.qfGroundMeaningCode_correct
#check @H10RationalGroundTests.witnessLabel_fresh
#check @H10RationalGroundTests.witnessLabel_injective
#check @H10RationalGroundTests.positiveExistentialFormula_semantics
#check @H10RationalGroundTests.poleParityFormula
#check @H10RationalGroundTests.rootQueryFormula_correct
#check @H10RationalGroundTests.rootQueryFormula_semantics
#check @H10RationalGroundTests.operationFormula_addition_semantics
#check @H10RationalGroundTests.operationFormula_multiplication_semantics
#check @H10RationalGroundTests.operationFormula_negation_semantics
#check @H10RationalGroundTests.primrec_operationFormula
#check @H10RationalGroundTests.functionCongruenceFormula_semantics
#check @H10RationalGroundTests.testItemFormula_semantics
#check @H10RationalGroundTests.primrec_dnfFormula
#check @H10RationalGroundTests.primrec_decodeTestItem
#check @H10RationalGroundTests.primrec_finiteTestDNF_of_itemTranslator
#check @H10RationalGroundTests.makeFiniteTestFormula_computable_of_itemTranslator
#check @H10RationalGroundTests.finiteTestDNF_satisfies_iff_of_semantic_translators
#check @H10RationalGroundTests.makeFiniteTestFormula_correct
#check @H10RationalGroundTests.finiteTestSolvable_computable_of_h10Q
#check @H10RationalGroundTests.everyTestItem_isEnumerated
#print axioms H10FiniteTests.re_exists_nat_of_computable
#print axioms H10FiniteTests.failure_iff_not
#print axioms H10FiniteTests.complement_re_of_tests
#print axioms H10FiniteTests.computable_of_re_and_tests
#print axioms H10FiniteTests.decision_transfer
#print axioms H10FiniteTests.undecidable_target
#print axioms H10RationalCompiler.compile_correct
#print axioms H10RationalCompiler.constraintSystem_computable
#print axioms H10RationalCompiler.indexed_constraintSystem_computable
#print axioms H10RationalQueryAdapter.integerCoefficientValue_eq_intCast
#print axioms H10RationalQueryAdapter.normalizeToInteger_support_bounded
#print axioms H10RationalQueryAdapter.normalizeToInteger_preserves_roots
#print axioms H10RationalQueryAdapter.primrec_normalizeToInteger
#print axioms H10RationalQueryAdapter.rationalRoot_computable_of_h10Q
#print axioms H10RationalQueryAdapter.constraintSystem_computable_of_h10Q
#print axioms H10RationalQueryAdapter.indexed_constraintSystem_computable_of_h10Q
#print axioms H10RationalFormula.formula_to_dnf_correct
#print axioms H10RationalFormula.primrec_toDNF
#print axioms H10RationalFormula.formulaSatisfies_computable_of_h10Q
#print axioms H10RationalFormula.indexed_formulaSatisfies_computable_of_h10Q
#print axioms H10RationalGroundTests.primrec_evaluateTermCode
#print axioms H10RationalGroundTests.applicationTerm_injective
#print axioms H10RationalGroundTests.applicationTerm_gt_arg
#print axioms H10RationalGroundTests.applicationTerm_not_arg
#print axioms H10RationalGroundTests.qfGroundMeaningCode_correct
#print axioms H10RationalGroundTests.positiveExistentialFormula_semantics
#print axioms H10RationalGroundTests.poleParityFormula
#print axioms H10RationalGroundTests.primrec_skolemTerm
#print axioms H10RationalGroundTests.primrec_skolemPrefixStep
#print axioms H10RationalGroundTests.primrec_skolemPrefix
#print axioms H10RationalGroundTests.primrec_substituteTerm
#print axioms H10RationalGroundTests.primrec_substituteQFToken
#print axioms H10RationalGroundTests.rootPolynomialValue_eq_integerPolynomialValue
#print axioms H10RationalGroundTests.primrec_rootPolynomial
#print axioms H10RationalGroundTests.primrec_rootQueryFormula
#print axioms H10RationalGroundTests.rootQueryFormula_correct
#print axioms H10RationalGroundTests.rootQueryFormula_semantics
#print axioms H10RationalGroundTests.operationFormula_addition_semantics
#print axioms H10RationalGroundTests.operationFormula_multiplication_semantics
#print axioms H10RationalGroundTests.operationFormula_negation_semantics
#print axioms H10RationalGroundTests.primrec_operationFormula
#print axioms H10RationalGroundTests.functionCongruenceFormula_semantics
#print axioms H10RationalGroundTests.testItemFormula_semantics
#print axioms H10RationalGroundTests.primrec_dnfFormula
#print axioms H10RationalGroundTests.primrec_finiteTestDNF_of_itemTranslator
#print axioms H10RationalGroundTests.makeFiniteTestFormula_computable_of_itemTranslator
#print axioms H10RationalGroundTests.finiteTestDNF_satisfies_iff_of_semantic_translators
#print axioms H10RationalGroundTests.makeFiniteTestFormula_correct
#print axioms H10RationalGroundTests.finiteTestSolvable_computable_of_h10Q
